# This is a basic workflow to help you get started with Actions

name: Build Preview

# Controls when the workflow will run
on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "**/*.md"
      - "README.md"
      - "LICENSE"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "**/*.md"
      - "README.md"
      - "LICENSE"
    type:
      - synchronize
      - opened
      - reopened
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@3.2.0
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20240501
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          args: |
            -synctex=1 
            -interaction=nonstopmode 
            -halt-on-error 
            -file-line-error
          extra_fonts: |
            ./*.otf
            ./*.ttf

      - name: Get Time GMT+08:00
        shell: pwsh
        run: |
          $NowTime = [int32](Get-Date -UFormat "%s")
          $Zone = [int16](Get-Date -UFormat "%Z").ToString()
          $NeedTime = (8 - $Zone) * 60 * 60
          $Result = $NowTime - $NeedTime
          $Formated = (Get-Date -UnixTimeSeconds $Result -UFormat "%Y-%m-%d_%H.%M.%S").ToString()
          echo $Formated

          %Rename-Item -Path ./main.pdf -NewName ($Formated + ".pdf")

          "{TIME_FORMATTED}={$Formated}" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: $TIME_FORMATTED
          path: main.pdf
